resources: 
  - { type: kpr, path: src/main/resources/io/vertigo/easyforms/studio/application.kpr}
mdaConfig:
  projectPackageName: io.vertigo.easyforms
  targetGenDir : src/main/
  properties: 
    vertigo.domain.java: true
    vertigo.domain.java.generateDtResources: false
    vertigo.domain.sql: true
    vertigo.domain.sql.targetSubDir: javagen/sqlgen
    vertigo.domain.sql.baseCible: PotsgreSql
    vertigo.domain.sql.generateDrop: true
    vertigo.domain.sql.generateMasterData: true
    vertigo.task: true
    mermaid: true